parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/recommended'
root: true
env:
  node: true
  jest: true
rules:
  quotes:
    - 2
    - 'single'
    - 'avoid-escape'
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  max-len:
    - error
    - ignoreStrings: true
      ignoreTrailingComments: true
      ignoreComments: true
