env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
rules:
  max-len:
    - error
    - ignoreStrings: true
      ignoreTrailingComments: true
      ignoreComments: true
  require-jsdoc: 0
  react/no-unknown-property: off
